stages:
  - .pre
  - build
  - test

linter:
  stage: .pre
  image: node:16-alpine
  script:
    - npm install
    - npm lint

build-frontend:
  stage: build
  image: node:16-alpine
  script:
    - echo "Start building the app Front End"
    - cd client
    - npm install --legacy-peer-deps
    - echo "Build successfully!"
  artifacts:
    paths:
      - build
      - node_modules/

build-backend:
  stage: build
  image: node:16-alpine
  script:
    - echo "Start building the app Back end"
    - cd server
    - npm install --legacy-peer-deps
    - npm run build
    - echo "Build successfully!"
  artifacts:
    paths:
      - build
      - node_modules/

unit-test-website:
  stage: .pre
  image: node:16-alpine
  script:
    - echo "Running tests"
    - cd server
    - npm install --legacy-peer-deps
    - npm run test
    - echo "Tests finished"
