stages:
  - .pre
  - build
  - test
  - package
  - release
  - deploy

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

linter-backend:
  stage: .pre
  image: node:16-alpine
  script:
    - echo "Running the linter"
    - cd server
    - npm install @typescript-eslint/eslint-plugin@latest --save-dev --force
    - npm install --legacy-peer-deps
    - npm run lint
    - echo "Linter finished"

unit-test-backend:
  stage: .pre
  image: node:16-alpine
  script:
    - echo "Running unit-tests for back-end"
    - cd server
    - npm install --legacy-peer-deps
    - npm run test:unit
    - echo "unit-tests finished for back-end"

build-frontend:
  stage: build
  image: node:16-alpine
  script:
    - echo "Start building the app - Front End"
    - cd client
    - npm install --legacy-peer-deps
    - npm run build
    - echo $APP_VERSION > build/version.html
    - echo "Front end built successfully!"
  artifacts:
    paths:
      - build
      - node_modules/

build-backend:
  stage: build
  image: node:16-alpine
  script:
    - echo "Start building the app - Back end"
    - cd server
    - npm install --legacy-peer-deps
    - npm run build
    - echo "Back end built successfully!"
  artifacts:
    paths:
      - build
      - node_modules/

package-backend:
  image: docker:24.0
  services:
    - docker:24-dind
  stage: package
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo $CONTAINER_TEST_IMAGE
    - echo $CI_REGISTRY_IMAGE
    - docker build -t $CONTAINER_TEST_IMAGE ./server/
    - docker push $CONTAINER_TEST_IMAGE

release-image-backend:
  image: docker:24.0
  services:
    - docker:24-dind
  stage: release
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE

deploy-backend:
  image: docker:24.0
  services:
    - docker:24-dind
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CONTAINER_TEST_IMAGE ./server/
    - docker run -d -p 4001:4001 $CONTAINER_RELEASE_IMAGE
