# Docker Compose uses the docker-compose file to define and run multi-containers docker applications
# When running docker compose up :
  # Step 1 :  See the dependencies and check which service will start first (here is the db)

version: "3.9"
services:
  server:
    container_name: backend
    restart: always
    ports:
      - 4001:4001
      - 4002:4002
      - 4003:4003
      - 4006:4006
      - 4010:4010
      - 5555:5555
    env_file:
      - ./server/.env
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/server
      - /server/node_modules
      - /server/prisma
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - dev-db
    networks:
      - transcendance
  dev-db:
    image: postgres:14
    container_name: trans_pgres
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./server/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: trans
    networks:
      - transcendance
  client:
    container_name: frontend
    restart: always
    ports:
      - '3000:3000'
    build:
      context: client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app/client
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    links:
      - server
    depends_on:
      - server
    networks:
      - transcendance
  # nginx:
  #   image: nginx:alpine
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - client
  #     - server
  #   networks:
  #     - transcendance

volumes:
  data:

networks:
  transcendance:
