name: Test report
description: File about test report
title: "[Test]: "
labels: ["Test_Report"]
assignees:
  - Alicia-bites
  - BarrierAntho
  - ELKAMINA
body:
  - type: markdown
    attributes:
      value: |
        Please fill the test report to be able to test the features correctly
- type: textarea
  id: steps
  attributes:
    label: Validation steps
    description: "Please walk us through it step by step."
    placeholder: "Lets Rock Baby"
    value: |
      1.
      2.
      3.
      ...
    render: markdown
  validations:
    required: true
- type: textarea
  id: result
  attributes:
    label: Expected result
    description: "Please describre the expected result"
    placeholder: "Expected result"
    render: markdown
  validations:
    required: true
- type: markdown
  id: relation
  attributes:
    label: Issues relation
    description: "Please write the issue number"
    value: |
      - [ ]
      - [ ]
      - [ ]
      ...
    render: markdown
  validations:
    required: false