name: Implementing CI/CD

on:
  push:
    branches: [ test ]
  workflow_dispatch:


jobs:
  build:
    name: Building
    runs-on: ubuntu-latest
    
    
    steps:
    - name: Clone my repo
      uses: actions/checkout@v2
    
    
    - name: Installing Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    
    
    - name: Install NPM Packages
      run: npm ci #ci stands for clean install. Instead of, installing dependencies from node_modules cache, it installs dependencies from package-lock.json
    
    
    - name: Build project
      run: npm run build
    
    
    - name: Run tests
      run: npm run test
      
    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2 
      # uploads build files to be accessible across jobs
      with:
        name: production
        path: ./build


  deploy: # job 2 identifier
    name: Deploy
    needs: build 
  # the build job must succeed in order to run this job
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2 
      # downloads the uploaded build files
      with:
        name: production
        path: ./build

    - name: Deploy to Github pages
      uses: crazy-max/ghaction-github-pages@v2
      # action to deploy to GitHub Pages
      with:
        target_branch: gh-pages
        build_dir: ./build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  
  
